baseurl = "//chischaschos.github.io/"
languageCode = "en-us"
title = "chischaschos rocks"
theme = "nofancy"

[params]
    highlight="solarized_light"

[taxonomies]
    talk = "talks"
    flashcard = "flashcards"
    thought = "thoughts"

[author]
    name = "emmanuel delgado"
    github = "chischaschos"
    linkedin = "emmanueldelgado"
    gaID = "UA-21486770-1"
    twitter = "chischaschos"
