baseurl = "//chischaschos.github.io/"
languageCode = "en-us"
title = "chischaschos rocks"
theme = "nofancy"
disqusShortname = "chischaschos-rocks"

[params]
    highlight="solarized_light"
    topmenu="none"

[author]
    name = "emmanuel delgado"
    github = "chischaschos"
    linkedin = "emmanueldelgado"
    gaID = "UA-21486770-1"
    twitter = "chischaschos"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
